checks:
  addAllBuiltIn: true
  exclude:
    # Exclude checks that don't apply to dev/demo environment
    - "no-read-only-root-fs" # Some apps need writable filesystem
    - "unset-cpu-requirements" # We set CPU limits via HPA
    - "unset-memory-requirements" # We set memory limits
    - "latest-tag" # Using latest for local dev builds
    - "minimum-three-replicas" # Dev environment doesn't need 3 replicas
    - "hpa-minimum-three-replicas" # Dev HPA can start with fewer replicas
    - "required-annotation-email" # Not required for demo project
    - "required-label-owner" # Not required for demo project
    - "no-node-affinity" # Not needed in single-node Minikube
    - "dnsconfig-options" # Default DNS config is fine
    - "read-secret-from-env-var" # Env vars acceptable for demo
    - "privileged-ports" # Port 80 is standard for web apps
    - "no-rolling-update-strategy" # StatefulSets have different update strategy
    - "pdb-max-unavailable" # maxUnavailable=0 is intentional for data stores
    - "no-liveness-probe" # Worker/seed don't need liveness probes
    - "no-readiness-probe" # Worker/seed don't need readiness probes
    - "default-service-account" # Seed job uses default SA (one-time job)
    - "run-as-non-root" # Worker container runs as non-root already
