checks:
  addAllBuiltIn: true
  exclude:
    # Exclude checks that don't apply to our use case
    - "no-read-only-root-fs" # Some apps need writable filesystem
    - "unset-cpu-requirements" # We set CPU limits via HPA
    - "unset-memory-requirements" # We set memory limits
    - "required-label-app" # Custom check causing false positives
    - "required-security-context" # Custom check causing false positives
